import type { SpatialEntityConfig } from "../entities/types";

export const ZONE_DEFINITIONS: SpatialEntityConfig[] = [
  {
    id: "zone:pitch",
    name: "Stadium Pitch",
    type: "zone",
    position: [0, 0.5, 0],
    shape: "box",
    dimensions: [100, 1, 60],
    args: [100, 1, 60],
    color: "#2f855a",
    metadata: {
      description: "FIFA World Cup 2026 Regulation Pitch",
      capacity: 22,
      securityStatus: "clear",
      accessibilityFeatures: "Level access from underground tunnels",
    },
  },
  {
    id: "zone:north-stand",
    name: "North Stand",
    type: "zone",
    position: [0, 10, -80],
    shape: "box",
    dimensions: [80, 18, 20],
    args: [80, 18, 20],
    color: "#2c5282",
    metadata: {
      description: "General admission seating area and active supporter section",
      capacity: 18500,
      securityStatus: "clear",
      accessibilityFeatures: "Designated wheelchair spaces in Row 10",
    },
  },
  {
    id: "zone:south-stand",
    name: "South Stand",
    type: "zone",
    position: [0, 10, 80],
    shape: "box",
    dimensions: [80, 18, 20],
    args: [80, 18, 20],
    color: "#2c5282",
    metadata: {
      description: "General admission seating area and family zone",
      capacity: 18500,
      securityStatus: "clear",
      accessibilityFeatures: "Designated wheelchair spaces in Row 10",
    },
  },
  {
    id: "zone:east-stand",
    name: "East Stand",
    type: "zone",
    position: [80, 10, 0],
    shape: "box",
    dimensions: [20, 18, 80],
    args: [20, 18, 80],
    color: "#2c5282",
    metadata: {
      description: "Premium club seating and hospitality suites",
      capacity: 22000,
      securityStatus: "clear",
      accessibilityFeatures: "Elevator access to all tiers",
    },
  },
  {
    id: "zone:west-stand",
    name: "West Stand",
    type: "zone",
    position: [-80, 10, 0],
    shape: "box",
    dimensions: [20, 18, 80],
    args: [20, 18, 80],
    color: "#2c5282",
    metadata: {
      description: "Media center, broadcast suites, and executive seating",
      capacity: 15000,
      securityStatus: "clear",
      accessibilityFeatures: "Full ramp accessibility and tactile flooring",
    },
  },
  {
    id: "zone:vip",
    name: "VIP Executive Club",
    type: "zone",
    position: [-75, 14, 0],
    shape: "box",
    dimensions: [12, 6, 30],
    args: [12, 6, 30],
    color: "#b7791f",
    metadata: {
      description: "Exclusive suite level for FIFA dignitaries and VIP guests",
      capacity: 1200,
      securityStatus: "restricted",
      accessibilityFeatures: "Private direct elevator and level access",
    },
  },
  {
    id: "zone:concourse",
    name: "Main Concourse Ring",
    type: "zone",
    position: [0, 1.2, 0],
    shape: "ring",
    dimensions: [105, 115, 64],
    args: [105, 115, 64],
    color: "#4a5568",
    metadata: {
      description: "Circulation area connecting all stands, concessions, and services",
      capacity: 35000,
      securityStatus: "clear",
      accessibilityFeatures: "Wide, step-free access throughout the entire level",
    },
  },
  {
    id: "zone:parking",
    name: "North Parking Lot",
    type: "zone",
    position: [0, 0.05, -150],
    shape: "box",
    dimensions: [150, 0.1, 50],
    args: [150, 0.1, 50],
    color: "#718096",
    metadata: {
      description: "Public vehicle parking and rideshare drop-off hub",
      capacity: 2500,
      securityStatus: "clear",
      accessibilityFeatures: "120 designated accessible parking spots",
    },
  },
];

export const GATE_DEFINITIONS: SpatialEntityConfig[] = [
  {
    id: "gate:a",
    name: "Gate A (North Entrance)",
    type: "gate",
    position: [0, 1, -110],
    color: "#319795",
    metadata: {
      status: "open",
      accessibilityRamp: true,
      type: "standard",
      description: "Main north entry gate serving North Stand and North Parking",
    },
  },
  {
    id: "gate:b",
    name: "Gate B (East Entrance)",
    type: "gate",
    position: [110, 1, 0],
    color: "#319795",
    metadata: {
      status: "open",
      accessibilityRamp: false,
      type: "standard",
      description: "East entry gate serving East Stand and Club Level",
    },
  },
  {
    id: "gate:c",
    name: "Gate C (South Entrance)",
    type: "gate",
    position: [0, 1, 110],
    color: "#319795",
    metadata: {
      status: "open",
      accessibilityRamp: true,
      type: "standard",
      description: "Main south entry gate serving South Stand and public transport hub",
    },
  },
  {
    id: "gate:d",
    name: "Gate D (West Entrance - VIP)",
    type: "gate",
    position: [-110, 1, 0],
    color: "#d69e2e",
    metadata: {
      status: "restricted",
      accessibilityRamp: true,
      type: "vip",
      description: "West entry gate reserved for VIPs, media, and stadium operations",
    },
  },
];

export const POI_DEFINITIONS: SpatialEntityConfig[] = [
  // Medical
  {
    id: "poi:medical-01",
    name: "First Aid Station 1",
    type: "poi",
    position: [-20, 1.2, -100],
    metadata: {
      category: "medical",
      status: "operational",
      access: "public",
      description: "Fully staffed medical station equipped for emergency triage",
    },
  },
  {
    id: "poi:medical-02",
    name: "First Aid Station 2",
    type: "poi",
    position: [20, 1.2, 100],
    metadata: {
      category: "medical",
      status: "operational",
      access: "public",
      description: "Fully staffed medical station with direct ambulance transfer lane",
    },
  },
  // Restrooms
  {
    id: "poi:restroom-01",
    name: "North Concourse Restrooms",
    type: "poi",
    position: [-40, 1.2, -90],
    metadata: {
      category: "restroom",
      status: "operational",
      access: "public",
      description: "Public restrooms including baby-changing station and accessible cubicle",
    },
  },
  {
    id: "poi:restroom-02",
    name: "East Concourse Restrooms",
    type: "poi",
    position: [90, 1.2, -40],
    metadata: {
      category: "restroom",
      status: "operational",
      access: "public",
      description: "Gender-neutral, fully accessible restroom facilities",
    },
  },
  {
    id: "poi:restroom-03",
    name: "South Concourse Restrooms",
    type: "poi",
    position: [40, 1.2, 90],
    metadata: {
      category: "restroom",
      status: "operational",
      access: "public",
      description: "High-capacity public restrooms next to South Stand food court",
    },
  },
  {
    id: "poi:restroom-04",
    name: "West Concourse Restrooms (Accessible)",
    type: "poi",
    position: [-90, 1.2, 40],
    metadata: {
      category: "restroom",
      status: "operational",
      access: "public",
      description: "Priority accessible restrooms with hoist and changing table",
    },
  },
  // Food Courts
  {
    id: "poi:food-01",
    name: "East Food Hall",
    type: "poi",
    position: [90, 1.2, 40],
    metadata: {
      category: "food-court",
      status: "operational",
      access: "public",
      description: "Main food court with 12 local vendors and beverage stations",
    },
  },
  {
    id: "poi:food-02",
    name: "West Concessions",
    type: "poi",
    position: [-90, 1.2, -40],
    metadata: {
      category: "food-court",
      status: "operational",
      access: "public",
      description: "Snack bar and hot meal stands serving West Stand ticket holders",
    },
  },
  // Elevators
  {
    id: "poi:elevator-01",
    name: "West Lift Core A",
    type: "poi",
    position: [-75, 1.2, 15],
    metadata: {
      category: "elevator",
      status: "operational",
      access: "public",
      description: "High-speed elevator connecting Concourse, VIP suites, and Press box",
    },
  },
  {
    id: "poi:elevator-02",
    name: "East Lift Core B",
    type: "poi",
    position: [75, 1.2, -15],
    metadata: {
      category: "elevator",
      status: "operational",
      access: "public",
      description: "Elevator providing access from ground level to upper club seating",
    },
  },
  // Information
  {
    id: "poi:info-01",
    name: "Main Information Desk",
    type: "poi",
    position: [80, 1.2, 0],
    metadata: {
      category: "information",
      status: "operational",
      access: "public",
      description: "Tournament helper desk for translation, lost & found, and ticketing issues",
    },
  },
  // Exits
  {
    id: "poi:exit-01",
    name: "North Evacuation Exit",
    type: "poi",
    position: [0, 1.2, -120],
    metadata: {
      category: "exit",
      status: "operational",
      access: "public",
      description: "High-capacity emergency exit route opening to external muster point",
    },
  },
  {
    id: "poi:exit-02",
    name: "South Evacuation Exit",
    type: "poi",
    position: [0, 1.2, 120],
    metadata: {
      category: "exit",
      status: "operational",
      access: "public",
      description: "High-capacity emergency exit route leading to public transport plaza",
    },
  },
  // Parking
  {
    id: "poi:parking-vip",
    name: "VIP Parking Area",
    type: "poi",
    position: [-130, 0.1, 10],
    metadata: {
      category: "parking",
      status: "operational",
      access: "vip",
      description: "Secured vehicle area with direct access to VIP West Entrance",
    },
  },
];
