import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
  console.error("Missing Supabase environment variables.");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

const ZONES = ['north-gate', 'south-gate', 'sector-104', 'vip-lounge', 'concourse-east'];

async function simulate() {
  console.log("Starting simulation loop...");
  
  // eslint-disable-next-line no-constant-condition
  while (true) {
    try {
      // 1. Update zone densities
      for (const zoneId of ZONES) {
        if (Math.random() > 0.5) {
          const newThroughput = Math.floor(Math.random() * 500);
          const newDensity = newThroughput > 400 ? 'critical' : newThroughput > 200 ? 'high' : newThroughput > 50 ? 'medium' : 'low';
          await supabase.from("zones").update({ 
            throughput: newThroughput,
            crowd_density: newDensity 
          }).eq("id", zoneId);
        }
      }

      // 2. Update volunteer statuses
      const { data: volunteers } = await supabase.from("volunteer_status").select("id, battery, current_zone_id");
      if (volunteers) {
        for (const vol of volunteers) {
          if (Math.random() > 0.7) {
            const newBattery = Math.max(0, vol.battery - 1);
            const moveZone = Math.random() > 0.8;
            
            await supabase.from("volunteer_status").update({
              battery: newBattery,
              current_zone_id: moveZone ? ZONES[Math.floor(Math.random() * ZONES.length)] : vol.current_zone_id,
              last_active: new Date().toISOString(),
              workload: ["low", "optimal", "high"][Math.floor(Math.random() * 3)],
            }).eq("id", vol.id);
          }
        }
      }

      // 3. Occasionally spawn an incident
      if (Math.random() > 0.85) {
        console.log("Spawning incident...");
        await supabase.from("incidents").insert({
          title: "Simulation Incident",
          description: "An incident generated by the simulation.",
          status: "open",
          priority: ["low", "medium", "high"][Math.floor(Math.random() * 3)],
          location_zone_id: ZONES[Math.floor(Math.random() * ZONES.length)],
        });
      }

      // 4. Occasionally spawn a task
      if (Math.random() > 0.8) {
        console.log("Spawning task...");
        await supabase.from("tasks").insert({
          title: "Simulation Task",
          description: "A task generated by the simulation.",
          type: "assistance",
          priority: "medium",
          status: "pending",
        });
      }

    } catch (err) {
      console.error("Simulation error:", err);
    }
    
    // Wait for 5 seconds before the next iteration
    await new Promise(resolve => setTimeout(resolve, 5000));
  }
}

simulate();
